ip_forward: true
network_compression_threshold: 256
stats: 7bf41362-3c7c-4093-9d5f-88168af86d6d
groups:
  Mo_Jiang:
  - admin
  zhjf:
  - admin
  inapp:
  - admin
servers:
  Lobby:
    motd: Lobby
    address: localhost:25566
    restricted: false
  Survival:
    motd: Survival
    address: localhost:25567
    restricted: false
  Game_bw:
    motd: Game_bw
    address: localhost:25568
    restricted: false
  Game_bw1:
    motd: Game_bw1
    address: localhost:25569
    restricted: false
  Game_bw2:
    motd: Game_bw2
    address: localhost:25570
    restricted: false
  Game_bw3:
    motd: Game_bw3
    address: localhost:25571
    restricted: false
  Game_bw4:
    motd: Game_bw4
    address: localhost:25572
    restricted: false
  Game_bw5:
    motd: Game_bw5
    address: localhost:25573
    restricted: false
  Game_bw6:
    motd: Game_bw6
    address: localhost:25574
    restricted: false
  Game_bw7:
    motd: Game_bw7
    address: localhost:25575
    restricted: false
  Game_bw8:
    motd: Game_bw8
    address: localhost:25576
    restricted: false
  Game_bw9:
    motd: Game_bw9
    address: localhost:25577
    restricted: false
  Game_sg1058:
    motd: Game_sg1058
    address: localhost:25578
    restricted: false
  Game_sg1058_1:
    motd: Game_sg1058_1
    address: localhost:25579
    restricted: false
  Game_sg1058_2:
    motd: Game_sg1058_2
    address: localhost:25580
    restricted: false
  Game_sg1058_3:
    motd: Game_sg1058_3
    address: localhost:25581
    restricted: false
  Game_sg1058_4:
    motd: Game_sg1058_4
    address: localhost:25582
    restricted: false
  Kitbattle:
    motd: Kitbattle
    address: localhost:25584
    restricted: false
  Game_tr:
    motd: Game_tr
    address: localhost:25585
    restricted: false
  Game_tr1:
    motd: Game_tr1
    address: localhost:25586
    restricted: false
  Game_tr2:
    motd: Game_tr2
    address: localhost:25587
    restricted: false
  Game_tr3:
    motd: Game_tr3
    address: localhost:25588
    restricted: false
  Game_tr4:
    motd: Game_tr4
    address: localhost:25589
    restricted: false
  Game_tr5:
    motd: Game_tr5
    address: localhost:25590
    restricted: false
  Game_tr6:
    motd: Game_tr6
    address: localhost:25591
    restricted: false
  Game_tr7:
    motd: Game_tr7
    address: localhost:25592
    restricted: false
  jie_bi:
    motd: jie_bi
    address: localhost:12345
    restricted: false
  Server:
    motd: text
    address: localhost:12344
    restricted: false
  Prototype:
    motd: Prototype
    address: localhost:43161
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25565
  motd: PixelRealms
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
prevent_proxy_connections: false
permissions:
  default:
  - bungeecord.command.server
  admin:
  - bungeecord.command.alert
  - bungeecord.command.list
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - ab.all
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
